using Advent2023;
Console.Clear();
// new Day01().Go();
// new Day02().Go();
// new Day03().Go();
// new Day04().Go();
// new Day05().Go();
// new Day06().Go();
// new Day07().Go();
// new Day08().Go();
// new Day09().Go();
// new Day10().Go();
// new Day11().Go();
// new Day12().Go();
// new Day13().Go();
new Day14().Go();